<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Pigment.O2</text>


        <Action name="pigment_o2_color_00">
          <text>Color 0</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_01">
          <text>Color 1</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_02">
          <text>Color 2</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_03">
          <text>Color 3</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_04">
          <text>Color 4</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_05">
          <text>Color 5</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_06">
          <text>Color 6</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_07">
          <text>Color 7</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_08">
          <text>Color 8</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_09">
          <text>Color 9</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_color_10">
          <text>Color 10</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>


        <Action name="pigment_o2_key_1_minus">
          <text>Key 1 Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_key_1_plus">
          <text>Key 1 Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="pigment_o2_key_2_minus">
          <text>Key 2 Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_key_2_plus">
          <text>Key 2 Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="pigment_o2_key_3_minus">
          <text>Key 3 Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_key_3_plus">
          <text>Key 3 Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="pigment_o2_key_4_minus">
          <text>Key 4 Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_key_4_plus">
          <text>Key 4 Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="pigment_o2_lock_cmyk">
          <text>Lock CMYK</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pigment_o2_lock_kkk">
          <text>Lock Kelvin</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>


    </Actions>
</ActionCollection>
