<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Pigment.O</text>


        <Action name="action_sof_1_plus">
          <text>SOF Size Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="action_sof_1_minus">
          <text>SOF Size Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="action_sof_2_plus">
          <text>SOF Opacity Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="action_sof_2_minus">
          <text>SOF Opacity Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="action_sof_3_plus">
          <text>SOF Flow Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="action_sof_3_minus">
          <text>SOF Flow Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>


        <Action name="action_rgb_1_plus">
          <text>RGB Red Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="action_rgb_1_minus">
          <text>RGB Red Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="action_rgb_2_plus">
          <text>RGB Green Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="action_rgb_2_minus">
          <text>RGB Green Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>

        <Action name="action_rgb_3_plus">
          <text>RGB Blue Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="action_rgb_3_minus">
          <text>RGB Blue Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>


    </Actions>
</ActionCollection>
